# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecac7cb2fded5cad370afca733f77b5bcbad310703283beacf9ff0d93e92ce2f37fb56c09c305a038d7aa5416d9ef7ff1e2f8185123059832aa6b086cde680a7

test:
  secret_key_base: 888d332c95c9a8dc83cf7432eec08cf314b634e4696047423aefb9eb3ef7ea6849c80eeefa3027cf9ecbe35fc59444801ab63eac0305d951b25e4ebbc73dc8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
